export function landingCopy(locale: string) {
  const ja = locale === "ja"
  return ja ? jaCopy : zhCopy
}

const zhCopy = {
  home: {
    lead: "在东京校院",
    title: "结交最适合的伙伴",
    subtitle: "找回真实社交的温度，只为遇见志同道合的真朋友。",
    cards: [
      ["关于我们", "", "/organization", "green"],
      ["活动介绍", "", "/scripts", "gold"],
      ["如何参加", "", "/join", "sky"],
      ["常见问题", "", "/faq", "pink"],
    ],
  },
  about: {
    title: "关于我们",
    subtitle: "从东京出发，连接屏幕之外的有趣灵魂。竹溪社面向东京各校学生，结合创新互动社交模式，提供丰富线下活动，在真实世界相遇，回归最纯粹的社交。",
    belief: "一个实践解决社交问题的\n跨校社交类社团。",
    body: "我们把双人/多人活动、轻博弈玩法和线下场景放在一起，让第一次见面有话题可聊。",
    types: ["线下活动", "桌游剧本杀", "旅行探索", "节日聚会", "中文交流"],
    teamIntro: "我们秉持着同样的理念与价值观，努力让人与人之间的联结变得更加通畅。",
    follow: "小红书关注我们",
    quote: "",
  },
  activities: {
    title: "活动介绍",
    subtitle: "竹溪社为不同需求的玩家开设“大型线下活动”与“社交剧本活动”，通过大量原创活动方案，旨在为不同社交倾向的同学提供丰富的活动类别。",
    photoTitle: "大型活动",
    photoSubtitle: "旅行、聚餐、户外、节日和团建。",
    photoTags: ["旅行", "聚餐", "户外", "节日"],
    scriptTeaserTitle: "社交剧本类",
    scriptTeaserBody: "剧本杀、桌游、推理、沉浸。",
    scriptTeaserCta: "进入剧本库",
    note: "",
    libraryTitle: "公开剧本库",
    librarySubtitle: "",
    libraryEmpty: "剧本库正在整理中",
    libraryCta: "查看详情",
  },
  join: {
    title: "如何参与",
    subtitle: "按流程加入社团",
    steps: [
      ["添加社团微信", "微信扫描或小红书后台联系管理员"],
      ["填写入社信息", "为保障社团氛围与社员间的和谐，竹溪社将对每位玩家进行简单的面试"],
      ["面试邀约", "竹溪社将在全程保证玩家隐私信息的基础上，在面试环节进行详细的社团介绍与规则说明"],
      ["加入社团群", "面试通过后将进入大群接收各类活动通知，并建议补全个人信息以便更精准的匹配"],
      ["参加活动", "竹溪社将定期发布各类活动，选择感兴趣的活动并报名，期待各位的加入！"],
    ],
    comfortTitle: "微信联系",
    comfortBody: "添加管理员微信，入社流程和近期活动会统一说明。",
    ctaTitle: "期待你的加入",
    ctaBody: "在东京、结交适合你的伙伴。",
    button: "添加管理员微信",
    handleLabel: "微信 / 小红书同号",
  },
}

const jaCopy = {
  home: {
    lead: "大学生の",
    title: "長く続く交流圏",
    subtitle: "東京で、自分に合う仲間と出会う",
    cards: [
      ["私たちについて", "どんな場所か\nなぜ作ったか", "/organization", "green"],
      ["活動紹介", "大型活動\n社交シナリオ", "/scripts", "gold"],
      ["参加方法", "四つのステップで\n気軽に参加", "/join", "sky"],
      ["よくある質問", "費用と流れを\n先に確認", "/faq", "pink"],
    ],
  },
  about: {
    title: "私たちについて",
    subtitle: "インタラクティブな交流と対面活動を組み合わせた\n大学生向けサークルです。",
    belief: "交流の課題を実践的に解く\n大学横断のコミュニティです。",
    body: "2人/複数人の活動、軽い遊び、対面の場面を組み合わせて、初対面でも話しやすくします。",
    types: ["対面活動", "ボードゲーム", "旅行探索", "季節イベント", "中国語交流"],
    compareLeft: "他のコミュニティでは",
    compareRight: "竹渓社では",
    left: ["活動後に会話が続かない", "グループが静かになりがち", "初参加者が入りにくい", "一度きりで終わりやすい"],
    right: ["固定の活動場所とよい雰囲気", "活動後も食事や会話が続く", "初参加でも入りやすい", "長く遊べる友だちに出会いやすい"],
    teamIntro: "四つのチームで活動、発信、シナリオ、技術を支えています。",
    follow: "SNSでフォロー",
    quote: "",
  },
  activities: {
    title: "活動紹介",
    subtitle: "大型活動と社交シナリオ\n気になる入口から",
    photoTitle: "大型活動",
    photoSubtitle: "旅行、食事、アウトドア、季節の集まり。",
    photoTags: ["旅行", "食事", "アウトドア", "季節"],
    scriptTeaserTitle: "社交シナリオ",
    scriptTeaserBody: "シナリオ、卓遊、推理、没入。",
    scriptTeaserCta: "一覧へ進む",
    note: "",
    libraryTitle: "公開シナリオ一覧",
    librarySubtitle: "",
    libraryEmpty: "シナリオ一覧を整理中です",
    libraryCta: "詳細を見る",
  },
  join: {
    title: "参加方法",
    subtitle: "QRからスタッフへ\n流れに沿って参加",
    steps: [["公式WeChat追加", "QRからスタッフへ"], ["入会情報入力", "基本情報を共有"], ["グループ参加", "活動通知を受け取る"], ["活動に参加", "気になる回を選ぶ"]],
    comfortTitle: "WeChatで連絡",
    comfortBody: "QRからスタッフを追加すると、入会の流れと直近の活動を確認できます。",
    ctaTitle: "参加をお待ちしています",
    ctaBody: "東京で、自分に合う仲間と出会う。",
    button: "WeChatで連絡",
    handleLabel: "WeChat / 小紅書",
  },
}
