export const landingActivitiesCopy = {
  zh: {
    title: "活动介绍",
    subtitle: "竹溪社把线下聚会、城市探索、剧本桌游与正在筹备的兴趣班级连在一起，让不同社交节奏的人都能找到入口。",
    introLead: "竹溪社汇聚众多原创社交活动，把线下聚会、城市探索、剧本桌游与正在筹备的兴趣班级连在一起。",
    introDetail: "活动前我们将提供人数地点、玩法预算等详细说明；活动中我们会通过分组、任务、游戏等方式制造话题，完成破冰；活动后我们也会继续跟进，提供继续认识、再次组局和反馈体验的空间。我们力求避免初次见面时的尴尬与压力。",
    categoryTitle: "三种社交入口",
    categoryHint: "任选适合你的参与方式",
    photoTitle: "大型活动",
    photoTitleEn: "Large Events",
    photoSubtitle: "一次性认识更多同学，沉浸热闹的社群氛围",
    photoBody: "我们把城市变成舞台，提供周末出游、露天聚餐到节日派对等诸多活动，热闹有趣，也最容易遇见同频的人。",
    photoTags: ["旅行", "聚餐", "户外", "节日", "团建"],
    photoCta: "查看详情",
    scriptTeaserTitle: "社交剧本",
    scriptTeaserTitleEn: "Social Scripts",
    scriptTeaserSubtitle: "小范围、有主题，慢慢熟悉彼此",
    scriptTeaserBody: "更想在小范围里逐渐熟络？竹溪社提供以主题和任务为线索的剧本活动，在推理、角色扮演和桌游中自然破冰，慢热的人也能轻松融入，留下一起复盘的回忆。",
    scriptTeaserTags: ["剧本", "桌游", "推理", "沉浸"],
    scriptTeaserCta: "进入剧本库",
    collectiveTitle: "团体社交",
    collectiveTitleEn: "Collective Social",
    collectiveSubtitle: "根据年龄、爱好、兴趣等细分社交圈",
    collectiveBody: "竹溪社将建立类似班级制度，根据玩家的不同兴趣爱好等特点，构建小团体社交。此外学部生可以讨论校园美好与青春气息、硕博生们也可互相倾诉压力与烦恼。",
    collectiveTags: ["兴趣班级", "同龄伙伴", "班长带队"],
    collectiveCta: "查看班级构想",
    closing: "无论你想热闹相遇、在主题中慢慢熟悉，还是寻找可以相伴一学期的固定伙伴，都可以在竹溪社找到适合自己的参与方式。",
    note: "",
    libraryTitle: "公开剧本库",
    librarySubtitle: "",
    libraryEmpty: "剧本库正在整理中",
    libraryCta: "查看详情",
  },
  ja: {
    title: "活動紹介",
    subtitle: "対面イベント、街歩き、シナリオ遊びに、準備中の興味別クラスをつなぐ構想です。自分のペースに合う交流の入口を広げます。",
    introLead: "竹渓社は多彩なオリジナル交流活動を通して、対面の集まり、街歩き、シナリオ遊びに、準備中の興味別クラスをつなぐ構想です。",
    introDetail: "人数、場所、予算の案内から、当日のアイスブレイク、活動後の再集合まで、初対面の緊張を少しずつ下げていきます。",
    categoryTitle: "三つの交流スタイル",
    categoryHint: "自分に合う入口を選べます",
    photoTitle: "大型活動",
    photoTitleEn: "Large Events",
    photoSubtitle: "一度に多くの学生と出会い、にぎやかな空気を楽しむ",
    photoBody: "週末のお出かけ、食事会、季節イベントを通して、同じ温度感の人に出会いやすい入口です。",
    photoTags: ["旅行", "食事", "屋外", "季節", "チーム活動"],
    photoCta: "活動写真を見る",
    scriptTeaserTitle: "社交シナリオ",
    scriptTeaserTitleEn: "Social Scripts",
    scriptTeaserSubtitle: "少人数、テーマありで、ゆっくり互いを知る",
    scriptTeaserBody: "テーマやタスクを手がかりに、推理、ロールプレイ、ボードゲームの中で自然に会話が生まれます。",
    scriptTeaserTags: ["シナリオ", "卓遊", "推理", "没入"],
    scriptTeaserCta: "一覧へ進む",
    collectiveTitle: "グループ交流",
    collectiveTitleEn: "Collective Social",
    collectiveSubtitle: "年齢や趣味、関心から、もっと自分に合う交流の輪へ",
    collectiveBody: "学年や興味の近い人で小さな「クラス」をつくる仕組みを構想しています。同じ関心を持つ仲間が一学期を通して交流し、学部生はキャンパスの日常を、大学院生は研究生活の悩みも分かち合える場を目指します。",
    collectiveTags: ["興味別クラス", "同世代", "クラスリーダー"],
    collectiveCta: "クラス構想を見る",
    closing: "にぎやかに出会う、テーマの中でゆっくり知り合う、一学期を共にする仲間を見つける。竹渓社で自分に合う参加の形を選べます。",
    note: "",
    libraryTitle: "公開シナリオ一覧",
    librarySubtitle: "",
    libraryEmpty: "シナリオ一覧を整理中です",
    libraryCta: "詳細を見る",
  },
} as const
