export default defineAppConfig({
  pages: [
    'pages/index/index',
    'pages/profile/index',
    'pages/matches/index',
    'pages/profile/edit-identity',
    'pages/profile/edit-language',
    'pages/profile/edit-interests',
    'pages/profile/edit-personality',
    'pages/profile/edit-tags',
    'pages/profile/edit-more-interests',
    'pages/quiz/index',
    'pages/quiz/result',
    'pages/review/index',
    'pages/scripts/index',
    'pages/scripts/detail',
    'pages/interview/index',
    'pages/survey/index',
    'pages/activities/index',
    'pages/matches/detail',
  ],
  tabBar: {
    color: '#ABABAB',
    selectedColor: '#3C6E47',
    backgroundColor: '#ffffff',
    borderStyle: 'black',
    list: [
      {
        pagePath: 'pages/index/index',
        text: '首页',
        iconPath: 'assets/home.png',
        selectedIconPath: 'assets/home-active.png',
      },
      {
        pagePath: 'pages/profile/index',
        text: '我的',
        iconPath: 'assets/user.png',
        selectedIconPath: 'assets/user-active.png',
      },
    ],
  },
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#3C6E47',
    navigationBarTitleText: '竹溪社',
    navigationBarTextStyle: 'white',
  },
})
